import React, { useState, useMemo } from 'react';
import { IdeaResult, SavedBookmark } from '../types';
import RadarChartComponent from './RadarChart';
import ComparisonRadarChart from './ComparisonRadarChart';
import MarkdownRenderer from './MarkdownRenderer';
import ScoreComparison from './ScoreComparison';
import { cleanImprovedIdea } from '../utils/ideaCleaner';
import { showError, showSuccess } from '../utils/toast';
import { renderAdvocacyContent, renderSkepticismContent } from '../utils/contentRenderers';

interface ResultItemProps {
  result: IdeaResult;
  index: number;
  showDetailedResults: boolean;
  savedBookmarks: SavedBookmark[];
  onBookmarkToggle?: (result: IdeaResult, index: number) => void;
  structuredOutput: boolean;
}

const ResultItem: React.FC<ResultItemProps> = React.memo(({
  result,
  index,
  showDetailedResults,
  savedBookmarks,
  onBookmarkToggle,
  structuredOutput
}) => {
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set());
  const [isBookmarking, setIsBookmarking] = useState(false);
  const [isSharing, setIsSharing] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  // Reset local state when result changes
  React.useEffect(() => {
    setExpandedSections(new Set());
    setIsBookmarking(false);
    setIsSharing(false);
    setIsExporting(false);
  }, [result]);

  const toggleSection = (section: string) => {
    setExpandedSections(prev => {
      const newSet = new Set(prev);
      if (newSet.has(section)) {
        newSet.delete(section);
      } else {
        newSet.add(section);
      }
      return newSet;
    });
  };

  const isExpanded = (section: string) => expandedSections.has(section);

  const isBookmarked = useMemo(() => {
    if (!savedBookmarks || savedBookmarks.length === 0) {
      return false;
    }
    const ideaText = result.idea;
    const improvedIdeaText = result.improved_idea;

    return savedBookmarks.some(bookmark =>
      bookmark.text === ideaText || (improvedIdeaText && bookmark.text === improvedIdeaText)
    );
  }, [result, savedBookmarks]);

  const handleBookmark = async () => {
    if (onBookmarkToggle) {
      setIsBookmarking(true);
      try {
        await onBookmarkToggle(result, index);
      } finally {
        setIsBookmarking(false);
      }
    }
  };

  const handleShare = async () => {
    const ideaText = result.improved_idea || result.idea;
    const score = result.improved_score || result.initial_score;
    const isImproved = !!result.improved_idea;

    const shareText = `Check out this amazing ${isImproved ? 'improved ' : ''}idea:\n\n${ideaText}\n\nScore: ${score}/10${isImproved ? ' (improved)' : ''}\n\nGenerated by MadSpark AI`;

    setIsSharing(true);

    try {
      if (navigator.share && navigator.canShare && navigator.canShare({ text: shareText })) {
        await navigator.share({
          title: `MadSpark ${isImproved ? 'Improved ' : ''}Idea #${index + 1}`,
          text: shareText,
        });
      } else {
        await handleClipboardShare(shareText);
      }
    } catch (err: any) {
      if (err.name === 'AbortError') {
        return;
      }

      console.warn('Native sharing failed, trying clipboard:', err);
      try {
        await handleClipboardShare(shareText);
      } catch (clipboardErr) {
        console.error('All sharing methods failed:', clipboardErr);
        showError('Unable to share idea. Please try copying manually.');
      }
    } finally {
      setIsSharing(false);
    }
  };

  const handleClipboardShare = async (text: string) => {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(text);
        showSuccess('Idea copied to clipboard!');
      } else {
        const textArea = document.createElement('textarea');
        textArea.value = text;
        textArea.style.position = 'fixed';
        textArea.style.left = '-999999px';
        textArea.style.top = '-999999px';
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();

        try {
          const successful = document.execCommand('copy');
          if (successful) {
            showSuccess('Idea copied to clipboard!');
          } else {
            throw new Error('Copy command failed');
          }
        } finally {
          document.body.removeChild(textArea);
        }
      }
    } catch (err) {
      console.error('Clipboard operation failed:', err);
      const userWantsCopy = window.confirm(
        'Unable to copy automatically. Click OK to see the text to copy manually.'
      );
      if (userWantsCopy) {
        showError(`Please copy this text manually:\n\n${text}`);
      }
      throw err;
    }
  };

  const handleExport = async () => {
    setIsExporting(true);

    try {
      const exportData = {
        idea: result.idea,
        score: result.initial_score,
        critique: result.initial_critique,
        advocacy: result.advocacy,
        skepticism: result.skepticism,
        improved_idea: result.improved_idea,
        improved_score: result.improved_score,
        improved_critique: result.improved_critique,
        score_delta: result.score_delta,
        timestamp: new Date().toISOString()
      };

      const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `madspark-idea-${index + 1}-${Date.now()}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      await new Promise(resolve => setTimeout(resolve, 500));
      showSuccess('Idea exported successfully!');
    } catch (error) {
      console.error('Export failed:', error);
      showError('Failed to export idea. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 8) return 'bg-green-500';
    if (score >= 6) return 'bg-yellow-500';
    if (score >= 4) return 'bg-orange-500';
    return 'bg-red-500';
  };

  const getScoreLabel = (score: number) => {
    if (score >= 8) return 'Excellent';
    if (score >= 6) return 'Good';
    if (score >= 4) return 'Fair';
    return 'Needs Work';
  };

  return (
    <div className="p-6 fade-in">
      {/* Original Idea - Only show if detailed results enabled */}
      {showDetailedResults && (
        <>
          <div className="mb-6">
            <h3 className="text-lg font-medium text-gray-900 mb-2">
              💡 Original Idea #{index + 1}
            </h3>
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <MarkdownRenderer
                  content={result.idea}
                  className="text-gray-700 mb-4 leading-relaxed"
                />
              </div>

              {/* Original Score Badge */}
              <div className="ml-4 flex-shrink-0">
                <div className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium text-white ${getScoreColor(result.initial_score)}`}>
                  <span className="mr-1">⭐</span>
                  {result.initial_score}/10
                </div>
                <div className="text-xs text-gray-500 mt-1 text-center">
                  {getScoreLabel(result.initial_score)}
                </div>
              </div>
            </div>
          </div>

          {/* Score Comparison - Only show if detailed results enabled */}
          <ScoreComparison
            originalScore={result.initial_score}
            improvedScore={result.improved_score}
            delta={result.score_delta || 0}
          />
        </>
      )}

      {/* Improved Idea - Now collapsible */}
      <div className={`${showDetailedResults ? 'mt-6' : ''} border rounded-lg bg-green-50 border-green-200`}>
        <button
          type="button"
          onClick={() => toggleSection('improved')}
          className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-green-100 transition-colors rounded-t-lg"
          aria-expanded={isExpanded('improved')}
          aria-controls={`improved-content-${index}`}
        >
          <div className="flex items-center justify-between flex-1">
            <span className="text-lg font-medium text-green-900">
              🚀 Improved Idea #{index + 1}
            </span>

            {/* Score Badge in header */}
            <div className="flex items-center mr-4">
              <div className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium text-white ${getScoreColor(result.improved_score || 0)}`}>
                <span className="mr-1">⭐</span>
                {(result.improved_score || 0).toFixed(1)}/10
              </div>
              <div className="text-xs text-gray-500 ml-2">
                {getScoreLabel(result.improved_score || 0)}
              </div>
            </div>
          </div>

          <svg
            className={`h-5 w-5 text-green-700 transition-transform ${
              isExpanded('improved') ? 'rotate-180' : ''
            }`}
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            aria-label="Toggle improved idea section"
          >
            <title>Toggle improved idea section</title>
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        {isExpanded('improved') && (
          <div id={`improved-content-${index}`} className="p-4 pt-0">
            <MarkdownRenderer
              content={structuredOutput ? (result.improved_idea || '') : cleanImprovedIdea(result.improved_idea || '')}
              className="text-gray-700 leading-relaxed"
            />
          </div>
        )}
      </div>

      {/* Multi-dimensional Evaluation - Show immediately after improved idea when not showing detailed results */}
      {!showDetailedResults && result.multi_dimensional_evaluation && (
        <div className="mt-4 border rounded-lg">
          <button
            type="button"
            onClick={() => toggleSection('multidim-simple')}
            className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-gray-50 transition-colors rounded-t-lg"
            aria-expanded={isExpanded('multidim-simple')}
            aria-controls={`multidim-simple-content-${index}`}
          >
            <span className="font-medium text-gray-900">
              📊 Multi-Dimensional Evaluation
            </span>
            <svg
              className={`h-5 w-5 text-gray-500 transition-transform ${
                isExpanded('multidim-simple') ? 'rotate-180' : ''
              }`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-label="Toggle multi-dimensional evaluation"
            >
              <title>Toggle multi-dimensional evaluation</title>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
          {isExpanded('multidim-simple') && (
            <div id={`multidim-simple-content-${index}`} className="p-4">
          {/* Use comparison chart if both original and improved evaluations exist */}
          {result.improved_multi_dimensional_evaluation ? (
            <ComparisonRadarChart
              title="Original vs Improved Idea Comparison"
              originalLabel="Original Idea"
              improvedLabel="Improved Idea"
              originalScore={result.initial_score ?? undefined}
              improvedScore={result.improved_score ?? undefined}
              data={[
                {
                  dimension: 'Feasibility',
                  original: result.multi_dimensional_evaluation.dimension_scores?.feasibility || 5,
                  improved: result.improved_multi_dimensional_evaluation.dimension_scores?.feasibility || 5,
                  fullMark: 10
                },
                {
                  dimension: 'Innovation',
                  original: result.multi_dimensional_evaluation.dimension_scores?.innovation || 5,
                  improved: result.improved_multi_dimensional_evaluation.dimension_scores?.innovation || 5,
                  fullMark: 10
                },
                {
                  dimension: 'Impact',
                  original: result.multi_dimensional_evaluation.dimension_scores?.impact || 5,
                  improved: result.improved_multi_dimensional_evaluation.dimension_scores?.impact || 5,
                  fullMark: 10
                },
                {
                  dimension: 'Cost Effectiveness',
                  original: result.multi_dimensional_evaluation.dimension_scores?.cost_effectiveness || 5,
                  improved: result.improved_multi_dimensional_evaluation.dimension_scores?.cost_effectiveness || 5,
                  fullMark: 10
                },
                {
                  dimension: 'Scalability',
                  original: result.multi_dimensional_evaluation.dimension_scores?.scalability || 5,
                  improved: result.improved_multi_dimensional_evaluation.dimension_scores?.scalability || 5,
                  fullMark: 10
                },
                {
                  dimension: 'Risk Assessment',
                  original: result.multi_dimensional_evaluation.dimension_scores?.risk_assessment || 5,
                  improved: result.improved_multi_dimensional_evaluation.dimension_scores?.risk_assessment || 5,
                  fullMark: 10
                },
                {
                  dimension: 'Timeline',
                  original: result.multi_dimensional_evaluation.dimension_scores?.timeline || 5,
                  improved: result.improved_multi_dimensional_evaluation.dimension_scores?.timeline || 5,
                  fullMark: 10
                }
              ]}
            />
          ) : (
            /* Fallback to single chart if only original evaluation exists */
            <>
              <RadarChartComponent
                data={[
                  { dimension: 'Feasibility', score: result.multi_dimensional_evaluation.dimension_scores?.feasibility || 5, fullMark: 10 },
                  { dimension: 'Innovation', score: result.multi_dimensional_evaluation.dimension_scores?.innovation || 5, fullMark: 10 },
                  { dimension: 'Impact', score: result.multi_dimensional_evaluation.dimension_scores?.impact || 5, fullMark: 10 },
                  { dimension: 'Cost Effectiveness', score: result.multi_dimensional_evaluation.dimension_scores?.cost_effectiveness || 5, fullMark: 10 },
                  { dimension: 'Scalability', score: result.multi_dimensional_evaluation.dimension_scores?.scalability || 5, fullMark: 10 },
                  { dimension: 'Risk Assessment', score: result.multi_dimensional_evaluation.dimension_scores?.risk_assessment || 5, fullMark: 10 },
                  { dimension: 'Timeline', score: result.multi_dimensional_evaluation.dimension_scores?.timeline || 5, fullMark: 10 }
                ]}
              />
              <div className="mt-3 text-sm text-gray-600">
                <p>
                  <strong>Overall Score:</strong> {(result.multi_dimensional_evaluation.overall_score || 0).toFixed(1)}/10
                </p>
                <p>
                  <strong>Confidence:</strong> {result.multi_dimensional_evaluation.confidence_interval ?
                    `${result.multi_dimensional_evaluation.confidence_interval.lower.toFixed(1)} - ${result.multi_dimensional_evaluation.confidence_interval.upper.toFixed(1)}` :
                    'N/A'}
                </p>
              </div>
            </>
          )}
            </div>
          )}
        </div>
      )}

      {/* Expandable Sections */}
      <div className="space-y-3 mt-4">
        {/* Initial Critique - Only show if detailed results enabled */}
        {showDetailedResults && (
          <div className="border rounded-lg">
            <button
            type="button"
            onClick={() => toggleSection('critique')}
            className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
            aria-expanded={isExpanded('critique')}
            aria-controls={`critique-content-${index}`}
          >
            <span className="font-medium text-gray-900">
              🔍 Initial Critique
            </span>
            <svg
              className={`h-5 w-5 text-gray-500 transition-transform ${
                isExpanded('critique') ? 'rotate-180' : ''
              }`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-label="Toggle initial critique section"
            >
              <title>Toggle initial critique section</title>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
          {isExpanded('critique') && (
            <div id={`critique-content-${index}`} className="px-4 pb-3 text-gray-700 critique-text">
              <MarkdownRenderer content={result.initial_critique} />
            </div>
          )}
          </div>
        )}

        {/* Advocacy - Only show if detailed results enabled AND advocacy content exists */}
        {showDetailedResults && result.advocacy && result.advocacy.trim() !== '' && (
          <div className="border rounded-lg">
          <button
            type="button"
            onClick={() => toggleSection('advocacy')}
            className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
            aria-expanded={isExpanded('advocacy')}
            aria-controls={`advocacy-content-${index}`}
          >
            <span className="font-medium text-gray-900">
              ✅ Advocacy
            </span>
            <svg
              className={`h-5 w-5 text-gray-500 transition-transform ${
                isExpanded('advocacy') ? 'rotate-180' : ''
              }`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-label="Toggle advocacy section"
            >
              <title>Toggle advocacy section</title>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
          {isExpanded('advocacy') && (
            <div id={`advocacy-content-${index}`} className="px-4 pb-3 text-gray-700 critique-text">
              {renderAdvocacyContent(result.advocacy)}
            </div>
          )}
          </div>
        )}

        {/* Skepticism - Only show if detailed results enabled AND skepticism content exists */}
        {showDetailedResults && result.skepticism && result.skepticism.trim() !== '' && (
          <div className="border rounded-lg">
          <button
            type="button"
            onClick={() => toggleSection('skepticism')}
            className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
            aria-expanded={isExpanded('skepticism')}
            aria-controls={`skepticism-content-${index}`}
          >
            <span className="font-medium text-gray-900">
              ⚠️ Skeptical Analysis
            </span>
            <svg
              className={`h-5 w-5 text-gray-500 transition-transform ${
                isExpanded('skepticism') ? 'rotate-180' : ''
              }`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-label="Toggle skeptical analysis section"
            >
              <title>Toggle skeptical analysis section</title>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
          {isExpanded('skepticism') && (
            <div id={`skepticism-content-${index}`} className="px-4 pb-3 text-gray-700 critique-text">
              {renderSkepticismContent(result.skepticism)}
            </div>
          )}
          </div>
        )}

        {/* Logical Inference - Only show if detailed results enabled and logical inference is present */}
        {showDetailedResults && result.logical_inference && (
          <div className="border rounded-lg">
            <button
              type="button"
              onClick={() => toggleSection('logical-inference')}
              className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
              aria-expanded={isExpanded('logical-inference')}
              aria-controls={`logical-inference-content-${index}`}
            >
              <span className="font-medium text-gray-900">
                🧠 Logical Inference Analysis
              </span>
              <svg
                className={`h-5 w-5 text-gray-500 transition-transform ${
                  isExpanded('logical-inference') ? 'rotate-180' : ''
                }`}
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-label="Toggle logical inference section"
              >
                <title>Toggle logical inference section</title>
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>
            {isExpanded('logical-inference') && (
              <div id={`logical-inference-content-${index}`} className="px-4 pb-3 text-gray-700">
                {result.logical_inference.error ? (
                  <div className="text-red-600 font-medium">
                    ⚠️ {result.logical_inference.error}
                  </div>
                ) : (
                  <div className="space-y-4">
                    {/* Inference Chain */}
                    {result.logical_inference.inference_chain && result.logical_inference.inference_chain.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Inference Chain:</h4>
                        <ul className="space-y-1">
                          {result.logical_inference.inference_chain.map((step, stepIndex) => (
                            <li key={stepIndex} className="flex items-start">
                              <span className="text-blue-600 mr-2">→</span>
                              <span>{step}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Conclusion */}
                    {result.logical_inference.conclusion && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Conclusion:</h4>
                        <p className="text-gray-800 font-medium">{result.logical_inference.conclusion}</p>
                      </div>
                    )}

                    {/* Confidence */}
                    <div>
                      <h4 className="font-semibold text-gray-900 mb-2">Confidence:</h4>
                      <div className="flex items-center">
                        <div className="w-full bg-gray-200 rounded-full h-2 mr-3">
                          <div
                            className="bg-blue-600 h-2 rounded-full"
                            style={{ width: `${(result.logical_inference.confidence * 100)}%` }}
                          ></div>
                        </div>
                        <span className="text-sm font-medium text-gray-900">
                          {Math.round(result.logical_inference.confidence * 100)}%
                        </span>
                      </div>
                    </div>

                    {/* Improvements */}
                    {result.logical_inference.improvements && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Suggested Improvements:</h4>
                        <p className="text-gray-700">{result.logical_inference.improvements}</p>
                      </div>
                    )}

                    {/* Causal Chain */}
                    {result.logical_inference.causal_chain && result.logical_inference.causal_chain.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Causal Chain:</h4>
                        <ul className="space-y-1">
                          {result.logical_inference.causal_chain.map((cause, causeIndex) => (
                            <li key={causeIndex} className="flex items-start">
                              <span className="text-green-600 mr-2">⟹</span>
                              <span>{cause}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Implications */}
                    {result.logical_inference.implications && result.logical_inference.implications.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Implications:</h4>
                        <ul className="space-y-1">
                          {result.logical_inference.implications.map((implication, impIndex) => (
                            <li key={impIndex} className="flex items-start">
                              <span className="text-purple-600 mr-2">•</span>
                              <span>{implication}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Constraint Satisfaction */}
                    {result.logical_inference.constraint_satisfaction && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Constraint Satisfaction:</h4>
                        <div className="space-y-2">
                          {Object.entries(result.logical_inference.constraint_satisfaction).map(([constraint, score]) => (
                            <div key={constraint} className="flex items-center">
                              <span className="text-sm text-gray-700 w-1/3">{constraint.replace(/_/g, ' ')}:</span>
                              <div className="w-1/3 bg-gray-200 rounded-full h-2 mr-2">
                                <div
                                  className="bg-orange-500 h-2 rounded-full"
                                  style={{ width: `${score * 100}%` }}
                                ></div>
                              </div>
                              <span className="text-sm font-medium text-gray-900 w-1/3">
                                {Math.round(score * 100)}%
                              </span>
                            </div>
                          ))}
                          {result.logical_inference.overall_satisfaction && (
                            <div className="mt-2 pt-2 border-t border-gray-200">
                              <div className="flex items-center font-medium">
                                <span className="text-sm text-gray-900 w-1/3">Overall Satisfaction:</span>
                                <div className="w-1/3 bg-gray-200 rounded-full h-2 mr-2">
                                  <div
                                    className="bg-blue-600 h-2 rounded-full"
                                    style={{ width: `${result.logical_inference.overall_satisfaction * 100}%` }}
                                  ></div>
                                </div>
                                <span className="text-sm font-medium text-gray-900 w-1/3">
                                  {Math.round(result.logical_inference.overall_satisfaction * 100)}%
                                </span>
                              </div>
                            </div>
                          )}
                        </div>
                      </div>
                    )}

                    {/* Second Order Effects */}
                    {result.logical_inference.second_order_effects && result.logical_inference.second_order_effects.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Second Order Effects:</h4>
                        <ul className="space-y-1">
                          {result.logical_inference.second_order_effects.map((effect, effectIndex) => (
                            <li key={effectIndex} className="flex items-start">
                              <span className="text-indigo-600 mr-2">↪</span>
                              <span>{effect}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Trade-offs */}
                    {result.logical_inference.trade_offs && result.logical_inference.trade_offs.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Trade-offs:</h4>
                        <ul className="space-y-1">
                          {result.logical_inference.trade_offs.map((tradeOff, tradeIndex) => (
                            <li key={tradeIndex} className="flex items-start">
                              <span className="text-amber-600 mr-2">⚖</span>
                              <span>{tradeOff}</span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}

                    {/* Contradictions */}
                    {result.logical_inference.contradictions && result.logical_inference.contradictions.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-gray-900 mb-2">Contradictions:</h4>
                        <div className="space-y-2">
                          {result.logical_inference.contradictions.map((contradiction, contIndex) => (
                            <div key={contIndex} className="p-2 bg-red-50 border border-red-200 rounded">
                              <span className="text-red-700">⚠️ {JSON.stringify(contradiction)}</span>
                            </div>
                          ))}
                        </div>
                        {result.logical_inference.resolution && (
                          <div className="mt-2">
                            <h5 className="font-medium text-gray-800 mb-1">Resolution:</h5>
                            <p className="text-gray-700">{result.logical_inference.resolution}</p>
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* Improved Critique - Only show if detailed results enabled */}
        {showDetailedResults && (
          <div className="border rounded-lg">
          <button
            type="button"
            onClick={() => toggleSection('improved-critique')}
            className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
            aria-expanded={isExpanded('improved-critique')}
            aria-controls={`improved-critique-content-${index}`}
          >
            <span className="font-medium text-gray-900">
              ✨ Improved Idea Critique
            </span>
            <svg
              className={`h-5 w-5 text-gray-500 transition-transform ${
                isExpanded('improved-critique') ? 'rotate-180' : ''
              }`}
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              aria-label="Toggle improved critique section"
            >
              <title>Toggle improved critique section</title>
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </button>
          {isExpanded('improved-critique') && (
            <div id={`improved-critique-content-${index}`} className="px-4 pb-3 text-gray-700 critique-text">
              <MarkdownRenderer content={result.improved_critique} />
            </div>
          )}
          </div>
        )}

        {/* Multi-dimensional Evaluation - Show as expandable only in detailed mode */}
        {showDetailedResults && result.multi_dimensional_evaluation && (
          <div className="border rounded-lg">
            <button
              type="button"
              onClick={() => toggleSection('multidim')}
              className="w-full px-4 py-3 text-left flex items-center justify-between hover:bg-gray-50 transition-colors"
            >
              <span className="font-medium text-gray-900">
                📊 Multi-Dimensional Evaluation
              </span>
              <svg
                className={`h-5 w-5 text-gray-500 transition-transform ${
                  isExpanded('multidim') ? 'rotate-180' : ''
                }`}
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
                aria-label="Toggle multi-dimensional evaluation section"
              >
                <title>Toggle multi-dimensional evaluation section</title>
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>
            {isExpanded('multidim') && (
              <div className="p-4">
                {/* Use comparison chart if both original and improved evaluations exist */}
                {result.improved_multi_dimensional_evaluation ? (
                  <ComparisonRadarChart
                    title="Original vs Improved Idea Comparison"
                    originalLabel="Original Idea"
                    improvedLabel="Improved Idea"
                    originalScore={result.initial_score ?? undefined}
                    improvedScore={result.improved_score ?? undefined}
                    data={[
                      {
                        dimension: 'Feasibility',
                        original: result.multi_dimensional_evaluation.dimension_scores?.feasibility || 5,
                        improved: result.improved_multi_dimensional_evaluation.dimension_scores?.feasibility || 5,
                        fullMark: 10
                      },
                      {
                        dimension: 'Innovation',
                        original: result.multi_dimensional_evaluation.dimension_scores?.innovation || 5,
                        improved: result.improved_multi_dimensional_evaluation.dimension_scores?.innovation || 5,
                        fullMark: 10
                      },
                      {
                        dimension: 'Impact',
                        original: result.multi_dimensional_evaluation.dimension_scores?.impact || 5,
                        improved: result.improved_multi_dimensional_evaluation.dimension_scores?.impact || 5,
                        fullMark: 10
                      },
                      {
                        dimension: 'Cost Effectiveness',
                        original: result.multi_dimensional_evaluation.dimension_scores?.cost_effectiveness || 5,
                        improved: result.improved_multi_dimensional_evaluation.dimension_scores?.cost_effectiveness || 5,
                        fullMark: 10
                      },
                      {
                        dimension: 'Scalability',
                        original: result.multi_dimensional_evaluation.dimension_scores?.scalability || 5,
                        improved: result.improved_multi_dimensional_evaluation.dimension_scores?.scalability || 5,
                        fullMark: 10
                      },
                      {
                        dimension: 'Risk Assessment',
                        original: result.multi_dimensional_evaluation.dimension_scores?.risk_assessment || 5,
                        improved: result.improved_multi_dimensional_evaluation.dimension_scores?.risk_assessment || 5,
                        fullMark: 10
                      },
                      {
                        dimension: 'Timeline',
                        original: result.multi_dimensional_evaluation.dimension_scores?.timeline || 5,
                        improved: result.improved_multi_dimensional_evaluation.dimension_scores?.timeline || 5,
                        fullMark: 10
                      }
                    ]}
                  />
                ) : (
                  /* Fallback to single chart if only original evaluation exists */
                  <>
                    <RadarChartComponent
                      data={[
                        { dimension: 'Feasibility', score: result.multi_dimensional_evaluation.dimension_scores?.feasibility || 5, fullMark: 10 },
                        { dimension: 'Innovation', score: result.multi_dimensional_evaluation.dimension_scores?.innovation || 5, fullMark: 10 },
                        { dimension: 'Impact', score: result.multi_dimensional_evaluation.dimension_scores?.impact || 5, fullMark: 10 },
                        { dimension: 'Cost Effectiveness', score: result.multi_dimensional_evaluation.dimension_scores?.cost_effectiveness || 5, fullMark: 10 },
                        { dimension: 'Scalability', score: result.multi_dimensional_evaluation.dimension_scores?.scalability || 5, fullMark: 10 },
                        { dimension: 'Risk Assessment', score: result.multi_dimensional_evaluation.dimension_scores?.risk_assessment || 5, fullMark: 10 },
                        { dimension: 'Timeline', score: result.multi_dimensional_evaluation.dimension_scores?.timeline || 5, fullMark: 10 }
                      ]}
                    />
                    <div className="mt-3 text-sm text-gray-600">
                      <p>
                        <strong>Overall Score:</strong> {(result.multi_dimensional_evaluation.overall_score || 0).toFixed(1)}/10
                      </p>
                      <p>
                        <strong>Confidence:</strong> {result.multi_dimensional_evaluation.confidence_interval ?
                          `${result.multi_dimensional_evaluation.confidence_interval.lower.toFixed(1)} - ${result.multi_dimensional_evaluation.confidence_interval.upper.toFixed(1)}` :
                          'N/A'}
                      </p>
                    </div>
                  </>
                )}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Action Buttons */}
      <div className="mt-4 flex space-x-3">
        <button
          type="button"
          onClick={handleBookmark}
          disabled={isBookmarking}
          data-testid={`bookmark-${index}`}
          className={`inline-flex items-center px-3 py-2 border ${
            isBookmarking
              ? 'border-gray-300 bg-gray-100'
              : isBookmarked
                ? 'border-blue-500 bg-blue-50'
                : 'border-gray-300'
          } shadow-sm text-sm leading-4 font-medium rounded-md ${
            isBookmarking
              ? 'text-gray-400 cursor-not-allowed'
              : isBookmarked
                ? 'text-blue-700'
                : 'text-gray-700'
          } bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:hover:bg-gray-100`}>
          {isBookmarking ? (
            <svg className="h-4 w-4 mr-1.5 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
          ) : (
            <svg className="h-4 w-4 mr-1.5" fill={isBookmarked ? 'currentColor' : 'none'} viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 5a2 2 0 012-2h10a2 2 0 012 2v16l-7-3.5L5 21V5z" />
            </svg>
          )}
          {isBookmarking ? 'Bookmarking...' : isBookmarked ? 'Bookmarked' : 'Bookmark'}
        </button>

        <button
          type="button"
          onClick={handleShare}
          disabled={isSharing}
          className={`inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md ${
            isSharing
              ? 'text-gray-400 bg-gray-100 cursor-not-allowed'
              : 'text-gray-700 bg-white hover:bg-gray-50'
          } focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:hover:bg-gray-100`}>
          {isSharing ? (
            <svg className="h-4 w-4 mr-1.5 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
          ) : (
            <svg className="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" />
            </svg>
          )}
          {isSharing ? 'Sharing...' : 'Share'}
        </button>

        <button
          type="button"
          onClick={handleExport}
          disabled={isExporting}
          className={`inline-flex items-center px-3 py-2 border border-gray-300 shadow-sm text-sm leading-4 font-medium rounded-md ${
            isExporting
              ? 'text-gray-400 bg-gray-100 cursor-not-allowed'
              : 'text-gray-700 bg-white hover:bg-gray-50'
          } focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 disabled:hover:bg-gray-100`}>
          {isExporting ? (
            <svg className="h-4 w-4 mr-1.5 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
          ) : (
            <svg className="h-4 w-4 mr-1.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
          )}
          {isExporting ? 'Exporting...' : 'Export'}
        </button>
      </div>
    </div>
  );
});

export default ResultItem;